import type { Category, Product, Slide } from "./types";

export const seedCategories: Category[] = [
  {
    id: "c1",
    slug: "jars",
    name: "500g Cups",
    tagline: "½ KG sitndip cups — 12 per box",
    image: "/images/hazelnut-tub.png",
    kind: "regular",
  },
  {
    id: "c2",
    slug: "wholesale",
    name: "6kg Wholesale",
    tagline: "Bulk tubs for shops and kitchens",
    image: "/images/pistachio-tub.png",
    kind: "regular",
  },
  {
    id: "c3",
    slug: "bestsellers",
    name: "Our Best Sellers",
    tagline: "The cups everyone comes back for",
    image: "/images/lotus-tub.png",
    kind: "bestsellers",
  },
];

export const seedSlides: Slide[] = [
  {
    id: "s1",
    image: "/images/hero-sweet.jpg",
    eyebrow: "ISO certified · Made in Lebanon",
    title: "Sit down. Dip in.",
    buttonText: "Shop cups",
    buttonHref: "/shop",
  },
  {
    id: "s2",
    image: "/images/hero-sit.jpg",
    eyebrow: "Hazelnut, pistachio, Lotus, and more",
    title: "SitnDip chocolate cups",
    buttonText: "Shop cups",
    buttonHref: "/shop",
  },
];

export const seedProducts: Product[] = [
  {
    id: "p1",
    slug: "hazelnut-chocolate-500g",
    name: "Hazelnut Chocolate ½ KG",
    price: 3.5,
    description:
      "Classic sitndip hazelnut chocolate. ½ KG cup, 12 pieces per box ($33 per box). ISO-certified, made in Lebanon.",
    image: "/images/hazelnut-tub.png",
    collection: "jars",
    popular: true,
    bestseller: true,
    inStock: true,
    createdAt: "2026-09-22T10:00:00.000Z",
  },
  {
    id: "p2",
    slug: "peanut-butter-500g",
    name: "Peanut Butter ½ KG",
    price: 3.75,
    description:
      "Creamy sitndip peanut butter. ½ KG cup, 12 pieces per box ($35 per box). ISO-certified, made in Lebanon.",
    image: "/images/peanut-tub.png",
    collection: "jars",
    popular: true,
    bestseller: false,
    inStock: true,
    createdAt: "2026-09-22T10:01:00.000Z",
  },
  {
    id: "p3",
    slug: "white-chocolate-hazelnut-500g",
    name: "White Chocolate with Hazelnut ½ KG",
    price: 4,
    description:
      "Kinder-style white chocolate with hazelnut. ½ KG cup, 12 pieces per box ($41 per box). ISO-certified, made in Lebanon.",
    image: "/images/kinder-tub.png",
    collection: "jars",
    popular: true,
    bestseller: true,
    inStock: true,
    createdAt: "2026-09-22T10:02:00.000Z",
  },
  {
    id: "p4",
    slug: "pistachio-500g",
    name: "Pistachio ½ KG",
    price: 8,
    description:
      "Rich sitndip pistachio cream. ½ KG cup, 12 pieces per box ($81 per box). ISO-certified, made in Lebanon.",
    image: "/images/pistachio-tub.png",
    collection: "jars",
    popular: true,
    bestseller: true,
    inStock: true,
    createdAt: "2026-09-22T10:03:00.000Z",
  },
  {
    id: "p5",
    slug: "lotus-500g",
    name: "Lotus ½ KG",
    price: 4.25,
    description:
      "Lotus cookie butter sitndip. ½ KG cup, 12 pieces per box ($43 per box). ISO-certified, made in Lebanon.",
    image: "/images/lotus-tub.png",
    collection: "jars",
    popular: true,
    bestseller: true,
    inStock: true,
    createdAt: "2026-09-22T10:04:00.000Z",
  },
  {
    id: "p6",
    slug: "cookies-and-cream-500g",
    name: "Cookies & Cream ½ KG",
    price: 4,
    description:
      "Cookies and cream sitndip. ½ KG cup, 12 pieces per box ($34 per box). ISO-certified, made in Lebanon.",
    image: "/images/cookies-tub.png",
    collection: "jars",
    popular: true,
    bestseller: false,
    inStock: true,
    createdAt: "2026-09-22T10:05:00.000Z",
  },
  {
    id: "p7",
    slug: "hazelnut-chocolate-6kg",
    name: "Hazelnut Chocolate 6 KG",
    price: 30,
    description:
      "Wholesale sitndip hazelnut chocolate tub. 6 KG net weight. For shops, bakeries, and kitchens.",
    image: "/images/hazelnut-tub.png",
    collection: "wholesale",
    popular: false,
    bestseller: false,
    inStock: true,
    createdAt: "2026-09-22T10:06:00.000Z",
  },
  {
    id: "p8",
    slug: "lotus-6kg",
    name: "Lotus 6 KG",
    price: 40,
    description:
      "Wholesale sitndip Lotus cookie butter tub. 6 KG net weight. For shops, bakeries, and kitchens.",
    image: "/images/lotus-tub.png",
    collection: "wholesale",
    popular: false,
    bestseller: false,
    inStock: true,
    createdAt: "2026-09-22T10:07:00.000Z",
  },
  {
    id: "p9",
    slug: "white-chocolate-hazelnut-6kg",
    name: "White Chocolate with Hazelnut 6 KG",
    price: 38,
    description:
      "Wholesale Kinder-style white chocolate with hazelnut. 6 KG net weight. For shops, bakeries, and kitchens.",
    image: "/images/kinder-tub.png",
    collection: "wholesale",
    popular: false,
    bestseller: false,
    inStock: true,
    createdAt: "2026-09-22T10:08:00.000Z",
  },
  {
    id: "p10",
    slug: "pistachio-6kg",
    name: "Pistachio 6 KG",
    price: 78,
    description:
      "Wholesale sitndip pistachio cream. 6 KG net weight. For shops, bakeries, and kitchens.",
    image: "/images/pistachio-tub.png",
    collection: "wholesale",
    popular: false,
    bestseller: false,
    inStock: true,
    createdAt: "2026-09-22T10:09:00.000Z",
  },
  {
    id: "p11",
    slug: "white-chocolate-6kg",
    name: "White Chocolate 6 KG",
    price: 28,
    description:
      "Wholesale sitndip white chocolate tub. 6 KG net weight. For shops, bakeries, and kitchens.",
    image: "/images/white-tub.png",
    collection: "wholesale",
    popular: false,
    bestseller: false,
    inStock: true,
    createdAt: "2026-09-22T10:10:00.000Z",
  },
  {
    id: "p12",
    slug: "dark-chocolate-6kg",
    name: "Dark Chocolate 6 KG",
    price: 35,
    description:
      "Wholesale sitndip dark chocolate tub. 6 KG net weight. For shops, bakeries, and kitchens.",
    image: "/images/dark-tub.png",
    collection: "wholesale",
    popular: false,
    bestseller: false,
    inStock: true,
    createdAt: "2026-09-22T10:11:00.000Z",
  },
  {
    id: "p13",
    slug: "cookies-and-cream-6kg",
    name: "Cookies & Cream 6 KG",
    price: 34,
    description:
      "Wholesale sitndip cookies and cream tub. 6 KG net weight. For shops, bakeries, and kitchens.",
    image: "/images/cookies-tub.png",
    collection: "wholesale",
    popular: false,
    bestseller: false,
    inStock: true,
    createdAt: "2026-09-22T10:12:00.000Z",
  },
];
